- name: install httpd, mod_ssl, php
  yum:
    name: 
      - httpd
      - mod_ssl
      - php
    state: latest

- name: Configure incoming traffic https
  become: yes
  firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled

- name: Configure incoming traffic http
  become: yes
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled

- name: Ensure apache is running
  become: yes
  service:
    name: httpd
    state: started

- name: Set up index.html
  become: yes
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart apache
