- name: swappiness
  hosts: all
  become: yes
  tasks:      
    - name: Control Play Execution more
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: ansible_memory_mb.real.total > 2048

    - name: Control Play Execution less
      debug:
        msg: Server memory less than 2048MB
      when: ansible_memory_mb.real.total < 2048
